import json
import os
import re
from typing import Any, Dict, List, Optional, TypedDict

from langchain.chains import create_sql_query_chain
from langchain.prompts import ChatPromptTemplate
from langchain_community.tools.sql_database.tool import QuerySQLDatabaseTool
from langchain_community.utilities import SQLDatabase
from langchain_openai import ChatOpenAI
from langgraph.graph import END, StateGraph

OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "").strip()
ENABLE_REAL_AI = os.getenv("ENABLE_REAL_AI", "true").lower() == "true"


def _clean_sql(raw_sql: str) -> str:
    sql = raw_sql.strip()
    sql = re.sub(r"^```sql", "", sql, flags=re.IGNORECASE).strip()
    sql = re.sub(r"^```", "", sql).strip()
    sql = re.sub(r"```$", "", sql).strip()
    sql = sql.rstrip(";")
    return sql


def _is_safe_select(sql: str) -> bool:
    normalized = sql.strip().lower()
    if not normalized.startswith("select"):
        return False
    forbidden = [" insert ", " update ", " delete ", " drop ", " alter ", " truncate ", " create "]
    for token in forbidden:
        if token in f" {normalized} ":
            return False
    return True


def _build_llm() -> Optional[ChatOpenAI]:
    if not ENABLE_REAL_AI or not OPENAI_API_KEY:
        return None
    return ChatOpenAI(model=OPENAI_MODEL, temperature=0)


def run_langchain_assistant(question: str, context: Dict[str, Any], postgres_url: str) -> Optional[Dict[str, Any]]:
    llm = _build_llm()
    if llm is None:
        return None

    try:
        sql_db = SQLDatabase.from_uri(
            postgres_url,
            include_tables=["sales_stats", "minute_event_stats", "product_sales", "anomaly_alerts"],
        )

        sql_chain = create_sql_query_chain(llm, sql_db)
        sql_query = _clean_sql(sql_chain.invoke({"question": question}))

        query_result: Any = "No query executed"
        if _is_safe_select(sql_query):
            query_tool = QuerySQLDatabaseTool(db=sql_db)
            query_result = query_tool.invoke(sql_query)
        else:
            sql_query = "Blocked non-read-only SQL generated by model"

        prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    (
                        "You are RetailBrain, a senior ecommerce intelligence analyst. "
                        "Answer using only provided context and SQL evidence. "
                        "Return strict JSON with keys: answer (string), evidence (array of strings), "
                        "next_actions (array of strings)."
                    ),
                ),
                (
                    "human",
                    (
                        "Question: {question}\n\n"
                        "Context JSON:\n{context_json}\n\n"
                        "Generated SQL:\n{sql_query}\n\n"
                        "SQL Result:\n{sql_result}"
                    ),
                ),
            ]
        )

        message = prompt.format_messages(
            question=question,
            context_json=json.dumps(context, default=str),
            sql_query=sql_query,
            sql_result=str(query_result),
        )
        llm_output = llm.invoke(message).content

        payload = json.loads(llm_output)
        return {
            "answer": str(payload.get("answer", "No answer generated")),
            "evidence": [
                f"SQL used: {sql_query}",
                f"SQL result snapshot: {str(query_result)[:500]}",
                *[str(item) for item in payload.get("evidence", [])],
            ][:6],
            "next_actions": [str(item) for item in payload.get("next_actions", [])][:5],
            "workflow_trace": [
                "LangChainSQLAgent: generated read-only SQL query",
                "LangChainSQLAgent: executed SQL against analytics tables",
                "LLMReasoner: converted query evidence into business explanation",
            ],
        }
    except Exception as exc:
        return {
            "answer": "AI engine fallback triggered due to runtime issue.",
            "evidence": [f"LangChain error: {exc}"],
            "next_actions": [
                "Validate OPENAI_API_KEY and model access",
                "Retry question after service warmup",
            ],
            "workflow_trace": ["LangChainSQLAgent: failed and returned fallback payload"],
        }


class GraphState(TypedDict):
    question: str
    metrics: Dict[str, Any]
    previous: Dict[str, Any]
    alerts: List[Dict[str, Any]]
    top_products: List[Dict[str, Any]]
    trend_agent: Dict[str, Any]
    recommendation_agent: List[str]
    report_agent: str
    trace: List[str]


def run_langgraph_business_update(
    question: str,
    metrics: Dict[str, Any],
    previous: Dict[str, Any],
    alerts: List[Dict[str, Any]],
    top_products: List[Dict[str, Any]],
) -> Optional[Dict[str, Any]]:
    llm = _build_llm()
    if llm is None:
        return None

    def metrics_node(state: GraphState) -> GraphState:
        state["trace"] = state.get("trace", []) + ["MetricsNode: loaded current and previous KPI windows"]
        return state

    def trend_node(state: GraphState) -> GraphState:
        m = state["metrics"]
        p = state["previous"]
        state["trend_agent"] = {
            "conversion_delta": m.get("conversion_rate", 0) - p.get("conversion_rate", 0),
            "abandonment_delta": m.get("abandonment_rate", 0) - p.get("abandonment_rate", 0),
            "revenue_delta": m.get("total_revenue", 0) - p.get("total_revenue", 0),
        }
        state["trace"] = state.get("trace", []) + ["TrendNode: computed KPI deltas"]
        return state

    def recommendation_node(state: GraphState) -> GraphState:
        trend = state.get("trend_agent", {})
        recommendations = [
            "Inspect checkout/payment services if conversion drops.",
            "Validate traffic source quality during spikes.",
            "Prioritize inventory for top-selling products.",
        ]
        if trend.get("conversion_delta", 0) < 0:
            recommendations.insert(0, "Investigate checkout error logs and payment gateway latency immediately.")
        if trend.get("abandonment_delta", 0) > 0:
            recommendations.insert(0, "Run funnel analysis for cart-to-purchase drop-off.")
        state["recommendation_agent"] = recommendations[:5]
        state["trace"] = state.get("trace", []) + ["RecommendationNode: generated operational actions"]
        return state

    def report_node(state: GraphState) -> GraphState:
        prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    "You are a concise executive commerce analyst. Return only one paragraph summary.",
                ),
                (
                    "human",
                    (
                        "User ask: {question}\n"
                        "Metrics: {metrics}\n"
                        "Trend deltas: {trend}\n"
                        "Alerts: {alerts}\n"
                        "Top products: {top_products}\n"
                        "Actions: {actions}"
                    ),
                ),
            ]
        )
        msg = prompt.format_messages(
            question=state["question"],
            metrics=json.dumps(state["metrics"], default=str),
            trend=json.dumps(state.get("trend_agent", {}), default=str),
            alerts=json.dumps(state.get("alerts", []), default=str),
            top_products=json.dumps(state.get("top_products", []), default=str),
            actions=json.dumps(state.get("recommendation_agent", []), default=str),
        )
        summary = llm.invoke(msg).content
        state["report_agent"] = summary
        state["trace"] = state.get("trace", []) + ["ReportNode: generated final executive summary"]
        return state

    try:
        graph = StateGraph(GraphState)
        graph.add_node("metrics", metrics_node)
        graph.add_node("trend", trend_node)
        graph.add_node("recommendation", recommendation_node)
        graph.add_node("report", report_node)

        graph.set_entry_point("metrics")
        graph.add_edge("metrics", "trend")
        graph.add_edge("trend", "recommendation")
        graph.add_edge("recommendation", "report")
        graph.add_edge("report", END)

        app = graph.compile()
        final_state = app.invoke(
            {
                "question": question,
                "metrics": metrics,
                "previous": previous,
                "alerts": alerts,
                "top_products": top_products,
                "trend_agent": {},
                "recommendation_agent": [],
                "report_agent": "",
                "trace": [],
            }
        )

        return {
            "metrics_agent": {
                "window": metrics.get("window_minutes"),
                "revenue": metrics.get("total_revenue"),
                "purchases": metrics.get("total_purchases"),
                "conversion_rate": metrics.get("conversion_rate"),
                "abandonment_rate": metrics.get("abandonment_rate"),
            },
            "trend_agent": final_state.get("trend_agent", {}),
            "alert_agent": alerts,
            "recommendation_agent": final_state.get("recommendation_agent", []),
            "report_agent": final_state.get("report_agent", "No report generated"),
            "workflow_trace": final_state.get("trace", []),
        }
    except Exception:
        return None
